added ShoppingCart model
vadymhrnk/book-store pull request #10
Opened 2024-01-02 15:20 UTC by vadymhrnk

2024-01-02 20:18 UTC, TarasYurkovskyi approved these changes
marvelous job!

2024-01-02 20:18 UTC, TarasYurkovskyi commented on src/main/java/com/example/bookstore/dto/UpdateCartItemQuantityRequestDto.java
> +    @Min(0)
i think it is better to make min 1

2024-01-03 08:16 UTC, d1sam requested changes
good job, but some changes should be done!

2024-01-03 08:16 UTC, d1sam commented on src/main/java/com/example/bookstore/controller/ShoppingCartController.java
> +            @RequestBody AddCartItemRequestDto requestDto,
```suggestion
            @RequestBody @Valid AddCartItemRequestDto requestDto,
```

2024-01-03 08:16 UTC, d1sam commented on src/main/java/com/example/bookstore/dto/UpdateCartItemQuantityRequestDto.java
> +    @Min(0)
```suggestion
    @Positive
```

2024-01-03 13:22 UTC, vovasalyha requested changes
Looks good, but see a couple of comments.

2024-01-03 13:22 UTC, vovasalyha commented on src/main/java/com/example/bookstore/dto/AddCartItemRequestDto.java
> +    @NotBlank
Are you sure this annotation applicable to Long?

2024-01-03 13:22 UTC, vovasalyha commented on src/main/java/com/example/bookstore/dto/AddCartItemRequestDto.java
> +    @NotBlank
Are you sure this annotation applicable to int?

2024-01-03 13:22 UTC, vovasalyha commented on src/main/java/com/example/bookstore/model/CartItem.java
> +    @ManyToOne
Please avoid EAGER relations.

2024-01-03 13:22 UTC, vovasalyha commented on src/main/java/com/example/bookstore/model/CartItem.java
> +    @ManyToOne
Please avoid EAGER relations.

2024-01-03 13:22 UTC, vovasalyha commented on src/main/java/com/example/bookstore/model/ShoppingCart.java
> +    @OneToOne
Please avoid EAGER relations.

2024-01-03 13:22 UTC, vovasalyha commented on src/main/java/com/example/bookstore/repository/ShoppingCartRepository.java
> +    @Query("select cart from ShoppingCart cart "
You can use String blocks for such long concatenations to make it easier to read and mantain.

2024-01-03 13:22 UTC, vovasalyha commented on src/main/java/com/example/bookstore/service/ShoppingCartService.java
> +            Long id
In context of ShoppingCartService it's not obvious which ID it is. So be more specific
```suggestion
            Long cartItemId
```

2024-01-03 13:22 UTC, vovasalyha commented on src/main/java/com/example/bookstore/service/impl/ShoppingCartServiceImpl.java
> +    public ShoppingCartDto addBookToCart(AddCartItemRequestDto requestDto, Long userId) {
Don't forget about `Transaction` annotation.

2024-01-03 13:22 UTC, vovasalyha commented on src/main/java/com/example/bookstore/service/impl/ShoppingCartServiceImpl.java
> +    public ShoppingCartDto updateQuantity(
Don't forget about `Transaction` annotation.

2024-01-03 13:22 UTC, vovasalyha commented on src/main/java/com/example/bookstore/service/impl/ShoppingCartServiceImpl.java
> +    private User getUserById(Long userId) {
Shouldn't it be UserService responsibility? I would better use userService for it instead of adding this private method.

2024-01-04 08:40 UTC, d1sam approved these changes
Well done!

2024-01-04 11:31 UTC, merged