added tests for ShoppingCart
vadymhrnk/book-store pull request #14
Opened 2024-01-09 19:29 UTC by vadymhrnk

2024-01-09 20:41 UTC, DevIgork approved these changes
good job!

2024-01-10 08:51 UTC, yevheniisynytsia requested changes
Well done! Let's improve some of the tests

2024-01-10 08:51 UTC, yevheniisynytsia commented on src/test/java/com/example/bookstore/controller/ShoppingCartControllerTest.java
> +        Assertions.assertEquals(1, actual.getId());
comparing ids doesn't guarantee your logic is tested. Better use EqualsBuilder.reflectionEquals(expected, actual, "id");

2024-01-10 08:51 UTC, yevheniisynytsia commented on src/test/java/com/example/bookstore/repository/ShoppingCartRepositoryTest.java
> +        assertEquals(userId, shoppingCart.getUser().getId());
same here, no guarantees that your logic is tested properly and you return objects that are filled with everything you expect. Let's create `expected` object and compare expected and actual

2024-01-10 08:51 UTC, yevheniisynytsia commented on src/test/java/com/example/bookstore/service/impl/ShoppingCartServiceImplTest.java
> +        Book book = new Book();
with extending this logic you will probably have to move these objects outside of this test. I would better create them in `@BeforeAll` so that they are reusable in future

2024-01-10 08:51 UTC, yevheniisynytsia commented on src/test/java/com/example/bookstore/service/impl/ShoppingCartServiceImplTest.java
> +        when(bookRepository.findById(bookId)).thenReturn(Optional.of(book));
it is hard to read
please move this `when` to other `whens` so that they are a solid block

2024-01-10 08:51 UTC, yevheniisynytsia commented on src/test/java/com/example/bookstore/service/impl/ShoppingCartServiceImplTest.java
> +        assertTrue(EqualsBuilder.reflectionEquals(expectedDto, actualDto));
exclude id here

2024-01-11 11:46 UTC, yevheniisynytsia approved these changes
:fire:

2024-01-17 19:49 UTC, merged